"""agrego el resto de tablas

Revision ID: 60567f970dc4
Revises: f177c45c40d1
Create Date: 2024-10-23 19:20:04.429297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60567f970dc4'
down_revision = 'f177c45c40d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.DateTime(), nullable=True),
    sa.Column('salida', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicion_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_civil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('momento_carga', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_marca', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_tipo_membresia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_membresia'], ['tipos_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('momento_carga', sa.DateTime(), nullable=True),
    sa.Column('id_marca', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('id_tipo_membresia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_membresia'], ['tipos_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('id_provincia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=25), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('tipo_persona', sa.String(length=50), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('id_genero', sa.Integer(), nullable=True),
    sa.Column('id_est_civil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_est_civil'], ['estado_civil.id'], ),
    sa.ForeignKeyConstraint(['id_genero'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(length=25), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('cuit', sa.String(length=25), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_turnos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_turnos'], ['turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('actividad_fisica_actual', sa.String(length=50), nullable=True),
    sa.Column('motivo_inicio', sa.Text(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(length=25), nullable=True),
    sa.Column('razon_social', sa.String(length=50), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_cond_fiscal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['id_cond_fiscal'], ['condicion_fiscal.id'], ),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('num_compra', sa.Integer(), nullable=True),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_factura', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('id_tipo_factura', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_factura'], ['tipos_factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('num_venta', sa.Integer(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('id_tipo_factura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_factura'], ['tipos_factura.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_venta')
    op.drop_table('ventas')
    op.drop_table('detalles_factura')
    op.drop_table('detalles_compra')
    op.drop_table('feedbacks')
    op.drop_table('facturas')
    op.drop_table('compras')
    op.drop_table('proveedores')
    op.drop_table('evaluaciones_fisicas')
    op.drop_table('empleados')
    op.drop_table('clientes')
    op.drop_table('personas')
    op.drop_table('localidades')
    op.drop_table('provincias')
    op.drop_table('promociones')
    op.drop_table('productos')
    op.drop_table('membresias')
    op.drop_table('maquinas')
    op.drop_table('turnos')
    op.drop_table('tipos_membresia')
    op.drop_table('tipos_factura')
    op.drop_table('tarjetas')
    op.drop_table('sucursales')
    op.drop_table('roles')
    op.drop_table('paises')
    op.drop_table('metodos_pago')
    op.drop_table('marcas')
    op.drop_table('generos')
    op.drop_table('estado_civil')
    op.drop_table('descuentos')
    op.drop_table('condicion_fiscal')
    op.drop_table('categorias')
    op.drop_table('asistencias_cliente')
    # ### end Alembic commands ###
