"""actualizo Users

Revision ID: f177c45c40d1
Revises: 
Create Date: 2024-10-23 18:53:11.116421

"""
from werkzeug.security import generate_password_hash
from models import Usuario
from app import db

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f177c45c40d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('id_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    #creo un usuario por defecto, valido si ya existe alguno
    existing_user = Usuario.query.filter_by(username='admin').first()
    
    if not existing_user:
        admin_user = Usuario(
            username='admin',
            password_hash=generate_password_hash('admin'),
            id_admin=True,
            )
        
        db.session.add(admin_user)
        db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
